# docker compose -f docker-compose.cloud.yml up
services:
  app:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8070:8070"
      - "5174:5174"
    environment:
      PGHOST: ${PGHOST:-db}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT:-5432}
      PGSSLMODE: prefer
      VITE_API_URL: http://localhost:8070
    command: sh -c "corepack enable && yarn install && yarn workspaces foreach --parallel --interlaced --include where2go-backend --include where2go-frontend run dev"
