# docker compose -f docker-compose.cloud.yml up
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app-base
    command: sh -c "corepack enable && yarn install && yarn run build && yarn run dev"
